define([], function() {
  var strings = {
    "_jP9TaPNRkCXWU4OplNcN+w": {
      "AriaWebPartOrSectionEnterTemplate": "{0}. Ƥŕȅśş Ȇņťěř ţŏ ƞȁvıģąţě ıńśıđȅ ţħĕ {1}. Ŵĥĕņ įńŝīďē, ūšē Ǻŀţ+Ƒ10 ťơ ĝŏ ŧō ŧŏơĺƅåŕ, űśȅ Âļŧ+Ƥ ťō mōvę ƒŏčūś ťő ŧĥȇ ƿŗōƿĕŕţƴ ƿàňę âňď ůşě Ěšĉâƥě ţŏ ēxĩţ ťĥė {1}.  ",
      "CanvasZoneAriaGoToToolbar": "Ƥŕȇŝš ěńťȇř ţơ ƒōċųš ıƞśıđē ŧĥȅ ŵęƂ ƥåŕţ. Āƒţěŗ ƴōŭ ãŕě ĭŋ ťħȅ ŵėƃ ƥâŗŧ, ƿřěşš ėŝĉǻƿė ťơ řȇťūřƞ ŧő ŧĥē ťőōłƀāř.",
      "CanvasZoneAriaGoToWebPart": "Ƥřęşś ĕņťěŗ ŧơ ġő ŧŏ ŧĥē ŵĕƂ ƿąřŧ'ŝ ţōőŀƂăř, ȳōū ĉǻń ťĥȅŉ ƿŗēšş ĕşĉáƿȅ ŧŏ ŕęťŭŗŋ ĥȅřĕ.",
      "CanvasZoneAriaWebpartName": "{0} Ŵȇƀ Ƥáŕť",
      "ConfirmationDialogYes": "Ȳěś",
      "ConfirmationDialogNo": "Ŋơ",
      "DeleteZoneConfirmationDialogMessage": "Äŗē ƴőų šŭřē ɏơů ŵȃņť ťŏ đȇļēťě ŧħĭś şȅčŧįŏƞ āňď ęvěŗƴţĥīƞġ īń ıť?",
      "DeleteConfirmationDialogTitle": "Ɗēļēťȅ Ĉơņƒįŗmȃţıőņ",
      "DeleteConfirmationDialogMessage": "Ãŕȇ ƴōű ŝųŕę ŷőů ŵǻƞţ ŧơ đĕľěŧě ţħįş ŵėɓ ƥáŕť?",
      "TextWebPartPlaceholder": "Ŧȳƥȅ ŷŏųř ŧȅxŧ ħȇŗě",
      "TextWebPartDisplayName": "Ţȇxŧ",
      "TextWebpartDescription": "Ăđď ãňď ƒơŗmãŧ ţęxţ.",
      "WebpartToolbarConfigButtonTitle": "Ěđıţ ŵȇɓ ƿäřť",
      "ZoneToolbarConfigButtonTitle": "Ĕďīţ ŝěĉţįơŋ",
      "WebpartToolbarMoveButtonTitle": "Mővė ŵėƄ ƿåŕť",
      "ZoneToolbarMoveButtonTitle": "Mŏvė şėċţīőŋ",
      "WebpartToolbarDeleteButtonTitle": "Ďĕļĕţė ŵȇƂ ƥâŕŧ",
      "ZoneToolbarDeleteButtonTitle": "Ďęļȅťȇ šēċťĩőń",
      "ToolbarNavigationArrowKeys": "Ųśĕ äŗřōŵ ķȅŷš ŧō ƞăvįğăţē īƞśĭđė ťĥė ŧơōłƃåř.",
      "ToolboxAriaLoadingAlert": "Ŧħė ťōőļƅơx įŝ ľőąđīņğ ŵęɓ ƥãŕťŝ.",
      "ToolboxAriaLoadingFinishedAlert": "Ţħę ţőŏļƀơx ƒįņīśħȅđ ĺŏȃďįńģ ŵȇƅ ƿąŗţś.",
      "ToolboxErrorMessage": "Ţĥěŕȇ ŵăş âŉ ȇŗŕőř ƒȇťčħīņĝ ťħē ŵėƂ ƿäŗťş. Ňőţ äĺŀ ŵěƀ ƿäřŧŝ măŷ ƃě ãvãĭŀäƀĺė.",
      "ToolboxHintTitle": "Ǻđđ ȃ ņęŵ ŵėƄ ƥāŕţ",
      "ToolboxNavigationArrowKeys": "{0} Ūšȅ Ļēƒţ ơŕ Ʀıġħţ ţō ňăvĩģǻťȅ. Űŝē Ĕƞŧĕŗ ŧơ ãđđ ţħę šęľėćŧėđ ŵėƀ ƿäřť.",
      "CanvasItems": "{0} ĭŧėmş įƞ ţħě ťơőŀƂãŗ.||{0} įťěm īń ťĥĕ ťőőļƄǻŕ.||{0} ĩŧȇmş ıņ ŧĥě ŧŏōĺƃąŗ.",
      "CanvasItemsInterval": "0||1||2-",
      "ToolboxSectionHeader": "Šĕćťįơň ŀâŷōŭŧ",
      "ToolboxOneColumnPart": "Őņė ċōłųmŉ",
      "ToolboxTwoColumnPart": "Ţŵŏ ċơļűmņŝ",
      "ToolboxThreeColumnPart": "Ţĥŗěĕ ĉŏłűmŋŝ",
      "ToolboxOneThirdRightColumnPart": "Ŏņē-ţĥĩŗđ řįğħŧ ćőŀųmŉ",
      "ToolboxOneThirdLeftColumnPart": "Ōŋė-ţħįřđ łěƒŧ ćơĺũmń",
      "ToolboxFullWidthColumnPart": "Ƒűłĺ-ŵıđťħ ĉŏĺŭmń",
      "SectionPropertyPaneTitle": "Şȇċţĭŏņ",
      "SectionPropertyPaneColumnGroupName": "Ĺăȳơŭť ơƿŧīŏŋš",
      "ToolbarSelectZone": "Śĕľĕćť šěĉťıōń",
      "DragIconFallbackRTEText": "Ťęxţ",
      "DragZoneHandleTitle": "Ƥŗĕŝŝ Ėŉťȅŕ ŏř Śƥãčę ŧō ěņŧęŗ mōvė mơđė",
      "DragZoneMoveStarted": "Ƥŕȇşş ůƥ àřřơŵ ƙȅŷ ŧŏ mơvȇ ŭƿ ȁńď ďőŵƞ ǻŕŕőŵ ķēɏ ťơ mơvě ďőŵň. Ƥŕėšś Ėŉţēŕ ŧơ ĉőŋƒıŕm ŧĥȅ mōvȇ. Ƥŗęšś ęŝčäƥĕ ŧŏ čąňčěľ ŧħė mōvę. ",
      "DragZoneMoveComplete": "Mŏvěđ ŵěƂ ƥȃŗŧ ƒŗōm {0} ťő {1}. ",
      "DragZoneMoveCompleteZone": "Mővĕđ şėċţĩơņ ƒřơm {0} ţŏ {1}",
      "DragZoneMoveCancelled": "Mōvȅ ĥȃş Ƃȇȅƞ ćåƞčĕłļěđ.",
      "DragZoneMoveNotAllowedAriaLabel": "Ćȃņ'ŧ mơvė ãňŷ ƒůŗţĥĕŕ ıń ťħàţ ďįřĕĉţīŏń, ŏŕ mővē īŝ ńơţ àĺŀơŵěď ťō ţħâť şęċťįőŋ",
      "DragZoneMoveNotAllowed": "Mōvȅ ňŏŧ äłľơŵėđ",
      "DragZoneMoveInsideLevelControl": "Ƥơşıţıŏń {0}",
      "DragZoneMoveInsideLevelSection": "Ċŏĺųmņ {0}, ƿőśįţĭŏŋ {1}",
      "DragZoneMoveInsideLevelZone": "Šȇčťĩōŋ {0}, čơŀūmŋ {1}, ƥōşĩţĩơň {2}",
      "WebPartAriaLabel": "ŵěƂ ƥǻŗť",
      "SectionContextualAriaLabel": "{0}, {1} şȅĉŧīōƞ čōňţąīńıņğ {2}",
      "SectionAriaLabel": "ŝȇćţıŏň",
      "WebPartsInSectionLabel": "{0}, {1}",
      "ToolboxHintSectionTitleOnlyLayouts": "Ȁďď ă ŋȅŵ šěćŧĩŏň",
      "ToolboxHintTitleWithLayout": "Åďđ ȃ ŉĕŵ ŵęƅ ƥãřť ıň {0}",
      "ToolboxHintColumnOne": "ćŏļůmň ōņȇ",
      "ToolboxHintColumnTwo": "ćŏłųmŉ ţŵơ",
      "ToolboxHintColumnThree": "ĉŏļůmň ŧħŗěȇ",
      "EmptySectionAriaLabel": "ŉơ ŵěƅƥȃřţ",
      "SectionPositionAriaLabel": "Şėčťĩōƞ {0} ōƒ {1}",
      "CloseButtonAriaLabel": "Ĉľōşē",
      "DeleteConfirmationLabel": "{0} ĥăŝ ƀėęŋ đĕŀȇţȅď.",
      "NarrowModeDialogTitle": "Ŵıđěŋ ŷơūř ƃřŏŵşĕŕ ŵįŋđŏŵ",
      "NarrowModeDialogSubtitle": "Ĕďįţıńģ īś ňŏť ãvãīĺāƃľȅ ĩň â ŋâŗŗőŵ Ƃŕőŵšėř ŵıŋđŏŵ. Mãĸĕ ţħě ŵīņďŏŵ ŵįđȇř ţő čơņţīńųě ĕďīţĭņĝ.",
      "DialogDescription": "{0} ďıäļőġ {1}"
    },
    "_yMeGkKybrchrRl4dKHORJw": {
      "FormattingBarAlignCenterButtonTitle": "Ĉēňťȇř",
      "FormattingBarAlignLeftButtonTitle": "Ȃĺīģń ļēƒţ",
      "FormattingBarAlignRightButtonTitle": "Ȁĺīģņ ŕıģħţ",
      "FormattingBarBoldButtonTitle": "ßőĺđ (Ćţřł+ʙ)",
      "FormattingBarBulletListButtonTitle": "ʙųļļēţėď łĭŝŧ",
      "FormattingBarClearFormattingButtonTitle": "Čľęȃŗ áļľ ƒōŗmąŧťīňĝ",
      "FormattingBarConfirmAction": "Ȁćţĩőņ {0} ƥęŕƒōŕmėď.",
      "FormattingBarConfirmActionOnSelection": "Āčŧīōƞ {0} ƿěŗƒŏŗmėđ ōň ŝěļėĉŧěđ ŧȇxŧ: {1}",
      "FormattingBarNormalTextButtonTitle": "Ɲŏŕmȃľ ŧěxŧ",
      "FormattingBarHeading2ButtonTitle": "Ĥĕāđĩņĝ 1",
      "FormattingBarHeading3ButtonTitle": "Ĥĕåđīňġ 2",
      "FormattingBarHeading4ButtonTitle": "Ħĕąďīňĝ 3",
      "FormattingBarQuoteButtonTitle": "Ƥůŀļ ǫůơţȇ",
      "FormattingBarItalicButtonTitle": "İŧȁŀīċ (Ćţŗŀ+Į)",
      "FormattingBarLinkButtonTitle": "Ħɏƥęŕļĩņķ",
      "FormattingBarNumberedListButtonTitle": "Ŋũmƀĕřȅď ľıśť",
      "FormattingBarUnderlineButtonTitle": "Ūňđĕŕŀıŉȅ (Čťŕļ+Ũ)",
      "FormattingBarUnlinkButtonTitle": "Ŕĕmŏvȅ ļįņĸ",
      "FormattingBarMoreButtonTitle": "Mőŕȇ",
      "UndoButtonTitle": "Ųńďō (Čťŗļ+Ž)",
      "RedoButtonTitle": "Ŗęďō (Čŧřľ+Ÿ)",
      "FormattingBarAccessibleLabel": "Ƒōŕmȃţţıńġ",
      "LinkDialogErrorNotSupportedLink": "Ťħĭŝ ļĩňƙ ţŷƥȅ ıš ŉơţ šůƥƥōŕţĕđ.",
      "LinkDialogTextFieldAriaLabel": "Ŵȇƃ ąďđŗěşş ţơ ŀīŋĸ ţơ",
      "LinkDialogTextFieldLabel": "ŴēƄ ăďďŗȇšŝ:",
      "LinkDialogDisplayTextFieldLabel": "Ťěxť ţō ďĩŝƥŀáɏ:",
      "LinkDialogTitle": "İņşęŗŧ ļīŉĸ",
      "RichTextEditorAriaLabel": "Ťēxţ ĕďĭţōř. Űšė Āŀţ+Ƒ10 ťơ ĝő ŧő ťőŏŀɓǻŕš.",
      "RichTextEditorTitle": "Ţěxť ěđīŧōŗ",
      "RichTextEditorIframeTitle": "{0} {1}",
      "RichTextLinkDialogCancelButtonLabel": "Ĉäńċĕľ",
      "RichTextLinkDialogSaveButtonLabel": "Šãvė",
      "RichTextNavigationAltF10Keys": "{0} {1}",
      "TextWebPartPlaceholder": "Ţƴƥě ƴơůŕ ťęxţ ĥȅŕě",
      "ToolbarNavigationArrowKeys": "Ũšę ȃřŕŏŵ ƙȅƴŝ ţŏ ňąvĩğāťȅ ıŋšıďě ţĥȅ ţơŏłƄäŗ.",
      "ToolbarNavigationTabKeys": "Ŭşĕ ţȃƃ ŧō šŵįťċħ ɓȇŧŵēĕŉ ťōŏĺɓăřş.",
      "ToolbarNavigationShiftTabKey": "Ŭśȅ śħīƒŧ + ŧàƀ ţō ņåvīğäŧȅ ƃåćƙ ťŏ ţĕxţƀōx",
      "ImagesWithTextNotSupported": "Ćāŋ'ť ƿâŝţĕ ımâġė ŵīťĥīŋ ŧęxŧ, ŧãƄľē, łĭşť őŕ mūĺťıƿłě ĩmäġęś äŧ ơňčě. Ƥľęåşȅ ƥȁšťę ȅåćĥ īmāğȅ\r\n    ıŋđĩvĩđůȃľĺȳ.",
      "ImagesInTableNotSupported": "***Ċȃń'ť ƿáşťȇ ĩmȃğė īŉŝıďē ŧâɓĺę. Īŋľĭŉē ımāģęś ăřė ŉŏŧ şűƿƥōŗŧęď.",
      "CloseWarningText": "Ćłơşę ŵȁŗƞįƞĝ {0} ",
      "LoadingText": "Ƥāŝţĭńģ...",
      "AddRowAboveText": "Īƞŝěřť äɓŏvē",
      "AddRowBelowText": "Ĭňşėřţ ɓȅĺőŵ",
      "DeleteRowText": "Ɗęłēŧė řōŵ",
      "AddColumnLeftText": "Ĩņšȇřŧ ľȇƒŧ",
      "AddColumnRightText": "Ĭƞŝěŕť řīĝĥŧ",
      "AddRowAboveShortcutText": "{0} (Čŧŗľ+Śĥĩƒţ+Ȃ)",
      "AddRowBelowShortcutText": "{0} (Čţŕļ+Şħįƒţ+Ž)",
      "DeleteRowShortcutText": "{0} (Ċŧŕļ+Ŝĥįƒť+Đ)",
      "RTESettingsText": "Ŧĕxţ àŋď ťåƅŀȅ ƒơŗmąťŧĭŋġ",
      "FontDropDownText": "Ƒōňť šţŷĺȅ",
      "StrikeThroughButtonLabel": "Ŝťŕĭķēţĥŕơũġħ",
      "SuperscriptButtonLabel": "Śŭƥėŕşčŕįƿţ",
      "SubscriptButtonLabel": "ŜůƄšĉřīƿţ",
      "ParagraphGroupText": "Ƥåŕáğŕãƥħ",
      "JustifyButtonLabel": "ĵũśţĭƒŷ",
      "IncreaseIndentButtonLabel": "Ĭńċřȅáśě īŉďēŋť",
      "DecreaseIndentButtonLabel": "Đȇĉřȅāšě ĭňďēŋţ",
      "FontSizeDropDownLabel": "Ƒơƞť ŝīżę",
      "TableTitle": "Ťàɓŀě",
      "TableGroupLabel": "Ţǻƃŀė (Ƥŕěvıĕŵ)",
      "TableGroup": "ŤǻƄŀĕ",
      "TableButtonLabel": "Ĩƞšȇŗť ťåƃŀĕ",
      "InsertAndDeleteGroupLabel": "Ĭňşĕřť ąƞď ďėļęťě",
      "InsertRowBeforeButtonLabel": "İŋşėŗţ ȃƄővĕ",
      "InsertRowAfterButtonLabel": "Ĭŉŝěŕŧ ƃĕļŏŵ",
      "InsertColumnLeftButtonLabel": "Ĩŉŝėŗţ łěƒŧ",
      "InsertColumnRightButtonLabel": "Ĭŋśȅŕť řĩĝħţ",
      "DeleteRowButtonLabel": "Ďĕļēţȅ ŕŏŵ",
      "DeleteColumnButtonLabel": "Ɖȇļėŧē čŏľūmņ",
      "DeleteTableButtonLabel": "Ɖēĺēţĕ ťåƄŀȅ",
      "FontColorLabel": "Ƒŏƞŧ ĉōĺơŗ",
      "StandardColorLabel": "Šŧáƞďȁŕđ ċőłŏŕš",
      "DefaultColorLabel": "Ȃūŧơmàťīċ",
      "RedDarkLabel": "Đäŗķ ŗěď",
      "RedLabel": "Ʀėď",
      "YellowLabel": "Ɏęļľơŵ",
      "GreenLightLabel": "Ŀĭğĥŧ ģŕęēń",
      "GreenLabel": "Ġřĕĕŉ",
      "GreenDarkLabel": "Ɖāřĸ ğŗěȇń",
      "BlueLightLabel": "Ĺįğĥŧ ƀŀűę",
      "BlueLabel": "Ɓļūȅ",
      "BlueDarkLabel": "Ɖȁŕķ ɓłůē",
      "PurpleLabel": "Ƥūŕƿľė",
      "HightlightLabel": "Ĥīğħĺĭġĥŧ ćōľơŗ",
      "HightlightColorsLabel": "Ħįģĥĺīĝħţ čŏŀŏřš",
      "PinkLabel": "Ƥĩŋĸ",
      "OrangeLabel": "Ōŕáƞġȇ",
      "RemoveHighlightColor": "Ŋŏ čŏľőŗ",
      "HyperlinkGroupLabel": "Ħƴƥęŗľĩŋƙ",
      "TealLabel": "Ţĕȃļ",
      "MagentaLabel": "Mǻğěňŧã",
      "AquaLabel": "Ąǫůā",
      "MaroonLabel": "Mãŗōōŋ",
      "GoldLabel": "Ĝơŀď",
      "GreyLabel": "Ĝŗĕƴ",
      "DarkGreyLabel": "Ɗãřķ ġřȅŷ",
      "BlackLabel": "ʙĺåćĸ",
      "ThemeColorGroupLabel": "Ŧĥēmě ċŏľơřş",
      "ThemeDarkerLabel": "Ŧħėmě ďāŗƙȇŕ",
      "ThemeDarkLabel": "Ŧħȇmȅ ďãŗķ",
      "ThemeDarkAltLabel": "Ťħȅmȇ đàřĸ ǻľŧėŗƞāťĕ",
      "ThemePrimaryLabel": "Ťĥėmě ƥřįmářȳ",
      "ThemeSecondaryLabel": "Ţĥȇmȇ šęċőňđåŕŷ",
      "NeutralDarkLabel": "Ňȅűţřȁĺ đåŕƙ",
      "NeutralPrimaryLabel": "Ŋęůťřȃŀ ƿŕīmąŕƴ",
      "NeutralPrimaryAltLabel": "Ŋȇũťřãĺ ƿŗĭmǻŕȳ áļťěŗŉȃţę",
      "NeutralSecondaryLabel": "Ńȅųťřäĺ şȅĉơńđǻŗȳ",
      "NeutralTertiaryLabel": "Ňęŭťŗȃŀ ŧȇŗŧĭȃŕƴ",
      "TableStylesGroupLabel": "Ťãƀłȇ śŧŷļēš",
      "SimpleTableButtonLabel": "Ƥľãīŉ",
      "TableWithHeaderBorderLabel": "ŚůƄťŀĕ ĥēąďȅŗ",
      "TableWithFilledHeaderLabel": "Ĥȅąđȇŕ",
      "TableWithBandedRowsLabel": "Ąŀţěŗŉáţĭŉğ ŗōŵŝ",
      "TableWithBandedRowsAndColumnsLabel": "Čōļųmň ħěåďĕŗ",
      "SimpleTableButtonThemeLabel": "Ŧħěmȇ-ċōłőřȇď ƥŀäĭň",
      "TableWithHeaderBorderThemeLabel": "Ŧĥęmě-ćőłőŕęđ śűƃŧĺė ħȇāďęŕ",
      "TableWithFilledHeaderThemeLabel": "Ťĥęmȇ-čŏĺőŗēď ĥȅąđěŕ",
      "TableWithBandedRowsThemeLabel": "Ţħȅmĕ-ĉőļōŕȇď ăĺŧȅřńáťīŋġ ŕōŵś",
      "TableWithBandedRowsAndColumnsThemeLabel": "Ţħēmȇ-ċōŀŏŗěđ ĉőŀũmŉ ħėáđęř",
      "AlignTableGroupLabel": "Ţăƀĺĕ āľĩġňmȅņť",
      "AlignTableLeftLabel": "Ăŀīģŋ ţâɓĺȅ ŀȅƒţ",
      "AlignTableCenterLabel": "Ȁŀĭġņ ţȃƄĺě ċĕƞťėŕ",
      "AlignTableRightLabel": "Ăļĩġŋ ŧäƃļē ŕĩğĥţ",
      "RTEPagePickerSaveAction": "Ţĥȇ ŀĭŉĸ {0} ĭś áđđȅď.",
      "RTEPagePickerUnlinkAction": "Ťħę ľĩŉķ {0} ıŝ ŗěmōvĕď."
    },
    "_/GZrHjuQO4erDQbBRI2XSA": {
      "DialogTitle": "İƞşĕŗţ łĭŋƙ",
      "UrlTextFieldLabel": "Áďďŕěšŝ",
      "UrlTextFieldAriaLabel": "Ŵĕƅ ąđďŗęŝś ťŏ ļįƞƙ ŧō",
      "UrlTextFieldError": "Ŧĥĭś ļīŋķ ťŷƿȇ ĩŝ ŋōť šųƥƥơřŧēđ.",
      "TitleTextFieldLabel": "Ţĕxţ ŧō đĭśƿŀāƴ",
      "RecentPagesLabel": "Mōŝŧ ŗȅčȇńţ ƿāğȅŝ ơń ţĥĩš śĩťĕ",
      "SearchForPagesLabel": "Ƥāģęś őņ ťĥĩš šĭŧě ťħȁť mǻţčĥ ƴōųř šȇåřčħ",
      "NoResultLabel": "Ňŏ ĭŧĕmş måŧćĥ ɏőŭř śęȁŕćħ",
      "TryAgainLabel": "Ťřȳ â ďīƒƒęřȇŋŧ ƙȅƴŵơŕđ",
      "OpenLinkInNewTabLabel": "Ŏƿȇň ĺĭńƙ ıƞ ã ņȇŵ ŧāƀ",
      "SaveButtonLabel": "Šàvė",
      "CancelButtonLabel": "Ċäŋćȇľ",
      "UnlinkButtonLabel": "Řėmơvě ĺĭňķ",
      "TitleSuggestionsColumnName": "Ťīŧĺĕ",
      "EditorSuggestionsColumnName": "Mőđĩƒĩėđ ƃȳ",
      "ModifiedSuggestionsColumnName": "Mōđįƒįěď",
      "PageContentContainsSearchText": "\"{0}\" ƒőųƞď ıƞ ƿàĝė ĉőŋťēŋŧś",
      "CurrentPage": "(čŭŗŕĕŉť ƥȁĝȇ)",
      "SearchTextFieldLabel": "Šȇăřćĥ",
      "SearchTextFieldPlaceholder": "Ȇƞťēř ĸęɏŵőŕďš ţơ śėąŗċħ ƒőŕ ƿâğęś ŏƞ ţħış şıŧě",
      "DialogAriaDescription": "Ĭńŝėŗţ â ļīńķ ťơ ą ƿàğě ơŉ ŧħė čūŗŕěňţ şıŧȇ ơŕ ŧơ ã ƥăģė ŏń ǻŋōţĥȇř şīťė.",
      "SuggestionsListAriaLabel": "Śȅĺȇčŧ ǻ ƿâĝė ƒŕơm ŧĥě {0} łīśţ. Ƥŕĕšş ŧħȅ Ųƥ âňđ Ɖōŵŉ áŗŗơŵ ķĕɏš ťō ƞăvīğāţę ŧĥŗơŭğħ ťĥē ƥåģęś. Ƥŕȇśŝ ţĥĕ Şƥăčė ĸȅȳ ţő šėľȅċţ ȃ ƿáĝė. Ŵĥęŋ ā ƿáģė ĭş ŝęļēĉţėď, ťĥę ƿăğė ļīŋķ ŵīŀľ ƀē űşėđ ĭƞ ŧĥȅ Ŀįňķ ĩŉƿűť Ƃŏx, åńđ, ĭƒ ťĥȇŕȇ įš ńō ťĕxť ĭƞ ţĥȅ Ţēxť ţō đıŝƥŀȁȳ įƞƥũţ ɓōx, ťĥĕ ƥâģē ţĩţłȇ ŵīłļ ƀě ůŝĕđ.",
      "SaveButtonDisabledScreenReaderAlert": "Ťħȅ Ŝàvē ɓűţťơŉ įş ňōť ávąīłȁƃľė Ƃęćåűşē ȁŉ ĩŋväĺīđ ŵȇƀ āďďŕēŝş ŵȃś ĕƞťēŗȇđ.",
      "SaveButtonEnabledScreenReaderAlert": "Ţĥȅ Śȃvȅ ƃűţŧōň ıš ȁvȃīľàƀĺĕ.",
      "PageIsSelectedScreenReaderAlert": "Ťĥē ƿȃğę {0} ĩş şȅļȇĉťēđ.",
      "IsSearching": "Śĕâřćĥīņġ...",
      "SearchResultsShowing": "Śęàřĉħ ŗęŝűľŧş ąŕę ďīšƿłåɏěď. Ƥřĕşş Ťȁƅ ŧő ġơ ŧō ťĥė Ŝėȁŕĉĥ řēşůļŧś łįŝţ.",
      "RecentPagesShowing": "Ȃ łīśţ ŏƒ ŗȇĉėńŧ ƥȃğȇş īś ďıŝƿľäƴēď. Ƥŕȅşş Ťâƃ ŧő ĝō ťŏ ŧħĕ Ŕȅčėņţ ƥâġěš ľĩśţ."
    },
    "_4SOrKBlkyRLkXWcT6txoow": {
      "ToolboxSearchAccessibleLabelTemplate": "Ţŷƿē ħȅřę ŧő šěăŕčĥ ƒőř ą ŵēɓ ƥäřť. {0}",
      "ToolboxSearchEscapeAccessibleLabel": "Ƥřėśš Ęśċȃƥę ťō ĉĺěåŕ ţħě ěxĩšŧıƞģ şȅàŕčħ.",
      "ToolboxSearchLabel": "Ŝęàŗĉĥ"
    },
    "_6tOZemhV08aF1IgNDNeiwQ": {
      "ToolboxGroupNameFullWidth": "Ȳőů ćàņ ąďđ őƞē őƒ ţĥȇśĕ ŵēƄ ƿȁŗţŝ ŧō ŧĥĭś ƒűľļ-ŵĭďŧħ ćŏĺűmƞ"
    },
    "_NS+5Kf9zpnH1/LStsp+Tfw": {
      "ToolboxCategoryTextMediaAndContent": "Ŧėxŧ, mȇďĩå, ąŋđ ćŏŋťȅŉŧ",
      "ToolboxCategoryDiscovery": "Ďıšċővęŕɏ",
      "ToolboxCategoryCommunicationAndCollaboration": "Ćőmműŉıĉǻťįơŉ ãňď ċŏłļäƄŏŕäťįōņ",
      "ToolboxCategoryPlanningAndProcess": "Ƥłǻŋňĭňğ âņđ ƥřőćȅşś",
      "ToolboxCategoryBusinessIntelligence": "Ɓűşįŋȇśś ȃňđ ĭńŧęŀĺıġĕńćȇ",
      "ToolboxCategorySiteTools": "Şįţę ťōŏļş",
      "ToolboxCategoryConnectors": "Ćơņŋęċťőřš",
      "ToolboxCategoryOther": "Ơţħȅŕ",
      "ToolboxGroupNameFeatured": "Ƒėăťűŗėđ",
      "ToolboxGroupNameAlphabetical": "Àľľ Å ţő Ƶ"
    },
    "_RRzf46hnc4+fBX8RHyocNg": {
      "TextWebPartDisplayName": "Ţĕxţ",
      "TextWebpartDescription": "Ąďđ ǻƞď ƒơřmâť ťēxŧ"
    },
    "_2TT4IG31kAjRqhD0h5kPOg": {
      "ToolboxGroupSeeAllButtonLabel": "Śęě äĺļ",
      "ToolboxGroupSeeAllButtonAriaLabel": "Şęě ăłł ŵĕƄ ƥäŗţŝ įņ {0}.",
      "ToolboxGroupAriaLabel": "{0} ľĭśŧ. Ūśė łęƒť ąņđ ŕīġĥť åŗŕōŵ ķęȳş ťő mơvē ŵĩŧħįń ŧĥĕ ļīšŧ."
    },
    "_WVn4QXYnL8WpGCqr2C9ySA": {
      "ToolboxCategoryAllCategory": "Àłŀ ɓƴ ćâţĕġōŗȳ",
      "ToolboxCategorySortingCategory": "Ăŀľ Å ţŏ Ź",
      "ToolboxCategorySearchResults": "Śęáŗĉĥ ŕėŝũľŧŝ",
      "ToolboxCollapseButtonDescription": "Řȇšťőŕȇ ŧơ ŏŕĭğīŋāļ šıźē",
      "NoResultLabel": "Ņő ĩţĕmś măţċĥ ŷơųŕ şĕäŕĉħ",
      "TryAgainLabel": "Ťŕƴ ȁ ďĭƒƒėŕĕƞţ ƙęɏŵōřđ",
      "LargeToolboxAriaTitle": "Ȅxƥąŉďėď ŵēɓ ƥåŗť ţōōłƀőx.",
      "LargeToolboxAriaSubTitle": "Ŧħȇŗē ářĕ {0} ıťėmš ıŉ ťĥē ťŏŏļƄōx.||Ţħĕřȅ ãŕě {0} ĭţěm ıƞ ťħȅ ťőōļƃơx.||Ţĥȇŗȅ ȃŗȅ {0} įťȅmś ĭŉ ťĥě ťőơļƃōx.",
      "ToolboxCollapseButtonAriaLabel": "Čōłŀąƿśě.",
      "CountStringIntervals": "0||1||2-",
      "DropDownMenuAriaLabel": "Şħőŵıŉĝ ŵȅƅ ƥǻŕťś ƒŗŏm {0} čăţěğōŗƴ.",
      "SwitchCategoryAlert": "Čĥãńĝēđ ťō {0}.",
      "BackButtonAriaLabel": "Ĝŏ Ƃąćķ ţơ ťĥȇ ƿřĕvįōŭś vįȅŵ."
    },
    "_CZsUWMvZilAKKAfwQSdzKQ": {
      "ToolboxExpandButtonTitle": "Ȅxƿǻŉď ţő şėȇ mơřė ŵȇƄ ƿâŗŧş",
      "ToolboxNoItemsFound": "Ŵē ċơųŀđŋ'ŧ ƒĭŋď ǻņŷťħĭŋģ ţħáŧ mǻŧċĥėş ɏőůŗ šĕąŕčĥ.",
      "ToolboxSectionHeader": "Ŝĕćŧīőŉ łăƴŏůţ",
      "CanvasItems": "{0} ŵĕɓ ƿăŗŧś đĩśƿļȁŷęď ĩŉ ŧĥē ťŏơłƀōx.||{0} ŵȇƂ ƿäřŧ đĭśƿłȁȳėđ īƞ ŧħē ŧŏŏŀƃơx.||{0} ŵęƅ ƿȁŗţś ďįŝƿľȁɏȅď īƞ ťĥę ţőŏľɓơx.",
      "CanvasItemsInterval": "0||1||2-"
    },
    "_NAR8NFw8cblGJm9t5CjqOw": {
      "SuccessfullyLoadedText": "Ŝůćĉęşšƒůĺŀȳ łơąđĕď ďȇɓůĝ mãƞıƒȇŝťš.",
      "ErrorLoadingText": "Ƒâīłėď ţŏ ľōāđ ďȅƂũğ mȃƞĩƒėšŧş: {0}"
    },
    "_vd/LT/qfiQhbHFfeM1GtlA": {
      "FetchFailedError": "***Ƒĕŧĉĥįņġ ŵȇƄƥăŧş ƒǻīŀėď ŵįťħ ȅřřőŕ \"{0}\". Ŗēňďėŕ ŏƒ á ċáċħęđ ŵőřƙɓĕƞčħ mǻŷ ƒāĩŀ."
    },
    "_FQya7ZjwIyrOEutOa+omIA": {
      "Title": "Ŵâŗńīƞģ",
      "SubText": "Ŷőūŗ ŵȅƄ ƥâŗŧ ŵįľļ ņōţ åƥƿĕǻŗ īň ŧħě ŧơơĺƅơx. Ƥŀȇąšĕ māƙȅ ŝůŗė \"ġũļƿ šėŗvě\" ĭş ŕūŉńıŋģ ıņ â ŵĕƃ ƿãŕţ ƥŗőĴēĉţ. Ƥŀěãśē ŗėƒŗēśħ ŧħě ƥăĝē őŉčė \"ģūļƿ şęŗvĕ\" īś řųňňıŉġ.",
      "OkButtonText": "ŌĶ",
      "ClickHerePrefix": "Ćľĩĉƙ ",
      "ClickHereLink": "ħȇŕě",
      "ClickHereSuffix": " ƒơŕ mơřĕ įŉƒơŗmȃŧĩŏň."
    },
    "_1JArBGDet5Uj9pJOV/9sFw": {
      "UrlTextBoxPlaceholder": "Ȅŉťěŗ ȃ ŪƦĻ ťơ vįȇŵ ĭŉ Mơɓıĺę Ƥŗĕvįęŵ Ťơŏŀ.",
      "ScreenReaderMobilePreviewEntered": "Ȳōū ħàvě ěňţęřȅď ŧħē MőƄıłȇ Ƥŕĕvįĕŵ Ŧőŏŀ. Ĭƒ ƴőŭ ŵáņť ťơ ƥŕėvįěŵ ǻ ďīƒƒēŗȇňŧ ƿǻğē, ėŋŧēŗ ţĥě ŬŔĻ ĭň ŬƦĹ ťėxť ƒįȇłď. Ŧō ċĺŏšė ťĥě ţơơĺ àńđ ğō ƅăčķ ťơ ŴơŗĸƄęƞĉĥ, ƿŗȇśš Ēşćǻƿȇ.",
      "ScreenReaderDevicePickerEntered": "Ůśȇ ĺȇƒţ åŉđ řīģħť ăřŕŏŵ ƙȇȳś ţŏ ĉĥŏŏšȇ ã ďȅvıćē ťơ ćħȃŉģę ţĥē ƥŕēvīēŵ šĉŕȅěń şīƶĕ.",
      "ScreenReaderDevicePickerSelectionChanged": "Ƥřėşş Ěņţėŗ ťő ĉħơőśȇ ţĥıś đēvīĉě.",
      "Width": "Ŵīďťħ",
      "Height": "Ĥēıģħţ"
    },
    "_8EVKOH1av6NjR/ZNfdafrw": {
      "WebPartData": "***Ŵėƀ Ƥȁŗť Ďȁŧǻ",
      "ClassicPages": "Čľąşšīĉ Ƥãģȇš",
      "ModernPages": "Mőđęŕƞ Ƥąĝēś",
      "Close": "Ćļōśě",
      "WebPartDataHelpInfoLink": "***Ĺȇąŗŉ åƄơűŧ ƥŕővĭŝįőŉĩŋģ ŠĥàŕĕƤŏıŉţ ǻśšȇťš ƒřőm ȳơũŗ ŠħâŕĕƤŏīƞţ ċľīȇńţ-śĭđȇ ŵȅɓ ƿǻŗţ"
    },
    "_IusqdbcSoVYQiit3+QRSxw": {
      "Office365Title": "Ŏƒƒįċȇ 365",
      "SharePointWorkbenchTitle": "ŜĥåŗėƤơĭńť Ŵőŕƙƅęƞĉĥ",
      "ScreenReaderDisplayModeSwitchToEditMode": "Šŵīŧĉĥęď ƒřŏm ƥŗęvīȅŵ mơđě ţő ȅďįť mőďę.",
      "ScreenReaderDisplayModeSwitchToReadMode": "Şŵīťčħȇď ƒŕőm ěđīť mōđȅ ţơ ƿřĕvĩĕŵ mŏďĕ."
    },
    "_nCtJlVOXBHa59LgYtajnjA": {
      "Save": "Ŝǻvė",
      "SaveAltText": "Ųšě ťő şävȅ ŧĥę ĉůŗŕēŉţ ŵōřķƅėņćĥ šťāŧȅ.",
      "Discard": "Ɗĭŝćȁřđ",
      "DiscardAltText": "Ũśȇ ŧő ďīśčăŕđ ŧħė čũŗŕĕńţ ŵōŕĸƂĕƞćħ śţāŧȇ.",
      "Mobile": "Mőƀįłĕ",
      "MobleAltText": "Ůŝē ťŏ ơƿęƞ ťħē mơƂįľě ƥŕĕvĩēŵ ťōŏľ ƒŏř á ĉėľĺ ƥĥőƞȅ.",
      "Tablet": "ŢăƄļȅť",
      "TabletAltText": "Ųŝȅ ťơ ōƥėņ ŧĥě mơƀıļȇ ƥŗȇvĩȅŵ ŧơőļ ƒőř ā ŧäƀľēŧ.",
      "Preview": "Ƥŕěvīȅŵ",
      "PreviewAltText": "Ũşě ŧơ ŝŵıţćĥ ƒřōm ěđīŧ mőďȇ ŧŏ ƥŕēvĩĕŵ mŏďȇ.",
      "Edit": "Ėďĭŧ",
      "EditAltText": "Ũŝě ťō šŵıŧĉħ ťō ĕđĩť mŏďē.",
      "WebPartData": "***Ŵėƃ ƿăŗŧ đăťǻ",
      "WebPartDataAltText": "***Ɖīśƿļàɏ ťĥȇ ŝȅŗįăłıżȇď ŵēƀ ƿâŕŧ ďǻţâ."
    }
  };

  strings.default = strings;
  return strings;
});