define([], function() {
  var strings = {
    "_jP9TaPNRkCXWU4OplNcN+w": {
      "AriaWebPartOrSectionEnterTemplate": "[!!--##{0}. Ƥŕěśş Ěƞťēŕ ŧō ŋăvĭģåťȅ ıŉšįđĕ ŧĥė {1}. Ŵħęƞ ıŋşĭđę, űşĕ Âľť+Ƒ10 ťơ ġŏ ţơ ţőōļƃāŕ, ŭšȇ Ąŀŧ+Ƥ ţŏ mơvě ƒőćūš ŧơ ţĥě ƥřőƥęřťŷ ƿāńē âƞď ūşė Ěŝċáƿȇ ţő ėxĩť ťħĕ {1}.  ##--!!]",
      "CanvasZoneAriaGoToToolbar": "[!!--##Ƥřȅşŝ ėŋŧęř ţő ƒŏĉūş īŋŝĭďĕ ŧħě ŵęƃ ƿàŗţ. Āƒŧėŗ ȳơų ăŗĕ ĩƞ ťħĕ ŵȇƃ ƿåŗť, ƥŕęŝš ėşċăƥȇ ŧő řęŧūŗŋ ŧő ťĥȅ ţơơłƃâŗ.##--!!]",
      "CanvasZoneAriaGoToWebPart": "[!!--##Ƥřȅŝŝ ȇņŧēř ťō ġŏ ŧơ ţĥě ŵēƅ ƥäŗť'š ťőőľƂāŕ, ȳơū čãƞ ŧĥěŋ ƿŕȇśş ėśćáƿē ŧŏ řęţűřņ ħēŕę.##--!!]",
      "CanvasZoneAriaWebpartName": "[!!--##{0} ŴěƄ Ƥāŗť##--!!]",
      "ConfirmationDialogYes": "[!!--##Ŷēŝ##--!!]",
      "ConfirmationDialogNo": "[!!--##Ńơ##--!!]",
      "DeleteZoneConfirmationDialogMessage": "[!!--##Ȃřȅ ŷŏŭ şųŕė ƴōų ŵăŋŧ ŧơ đěłȇţė ŧĥīŝ şȇćţıŏŋ ǻŋď ěvĕŗɏŧħįŋğ ĭƞ ĭť?##--!!]",
      "DeleteConfirmationDialogTitle": "[!!--##Ɖĕļěŧę Ćŏƞƒıřmãţıōŋ##--!!]",
      "DeleteConfirmationDialogMessage": "[!!--##Àŕė ɏơŭ śūřĕ ƴŏų ŵȁňŧ ťŏ ďęłěŧě ťĥıś ŵēɓ ƿȁřť?##--!!]",
      "TextWebPartPlaceholder": "[!!--##Ťŷƿĕ ŷōůŕ ŧĕxť ĥȅŕĕ##--!!]",
      "TextWebPartDisplayName": "[!!--##Ţęxţ##--!!]",
      "TextWebpartDescription": "[!!--##Ȃďď ȁńđ ƒőŕmȃŧ ŧěxŧ.##--!!]",
      "WebpartToolbarConfigButtonTitle": "[!!--##Ęďĩŧ ŵěƀ ƥąřť##--!!]",
      "ZoneToolbarConfigButtonTitle": "[!!--##Ěďĩť şȅčťĭőń##--!!]",
      "WebpartToolbarMoveButtonTitle": "[!!--##Mővě ŵēƂ ƿȁřŧ##--!!]",
      "ZoneToolbarMoveButtonTitle": "[!!--##Mővē śĕċťīŏń##--!!]",
      "WebpartToolbarDeleteButtonTitle": "[!!--##Ɗȅĺęťȇ ŵėƅ ƥăŕţ##--!!]",
      "ZoneToolbarDeleteButtonTitle": "[!!--##Ďėľĕťȇ ŝȇċťīơŋ##--!!]",
      "ToolbarNavigationArrowKeys": "[!!--##Űšȇ àřŗŏŵ ƙėŷŝ ťŏ ńävıĝáťě ĩƞšĩđĕ ţĥȅ ŧŏőŀƃǻŕ.##--!!]",
      "ToolboxAriaLoadingAlert": "[!!--##Ťħě ŧőōĺƄơx ĩś ļōãďįňġ ŵȅɓ ƥářţŝ.##--!!]",
      "ToolboxAriaLoadingFinishedAlert": "[!!--##Ťĥĕ ťŏōŀƃőx ƒıŋıšħėđ łơàďıŋğ ŵěƀ ƿȁřťš.##--!!]",
      "ToolboxErrorMessage": "[!!--##Ţħĕřē ŵåş äŋ ěŗřŏŗ ƒĕŧĉħĩņģ ţħȇ ŵȇƄ ƿäřťş. Ņőţ ǻłĺ ŵȅɓ ƥăŗŧś mǻɏ ƅę âvǻĩłąƄľė.##--!!]",
      "ToolboxHintTitle": "[!!--##Åđď ã ňėŵ ŵėƂ ƿąřŧ##--!!]",
      "ToolboxNavigationArrowKeys": "[!!--##{0} Ūšȅ Ĺęƒť ōř Ŗıģħť ţő ńåvįĝåŧē. Ũśė Ēńťěŗ ťơ ãđđ ťĥē şėļȇćţėđ ŵēƃ ƿãŕŧ.##--!!]",
      "CanvasItems": "[!!--##{0} ĭŧěmŝ ĭŉ ťħė ťơŏŀƄȃŕ.||{0} ĭťěm ıń ŧħĕ ŧőơłƅàŕ.||{0} įťȇmš ĭň ŧĥȅ ťŏōłƄâŕ.##--!!]",
      "CanvasItemsInterval": "[!!--##0||1||2-##--!!]",
      "ToolboxSectionHeader": "[!!--##Ŝėčŧįơŉ ļăƴŏũŧ##--!!]",
      "ToolboxOneColumnPart": "[!!--##Őŋȅ ĉơļůmņ##--!!]",
      "ToolboxTwoColumnPart": "[!!--##Ţŵő čŏľūmňş##--!!]",
      "ToolboxThreeColumnPart": "[!!--##Ťĥŗȅȇ ĉơľŭmƞş##--!!]",
      "ToolboxOneThirdRightColumnPart": "[!!--##Ōŉě-ţĥīřđ ŕīģħŧ ĉơļŭmƞ##--!!]",
      "ToolboxOneThirdLeftColumnPart": "[!!--##Ōŋě-ťħĭŗď ŀěƒŧ ćőľũmƞ##--!!]",
      "ToolboxFullWidthColumnPart": "[!!--##Ƒŭĺľ-ŵįďŧĥ ċőłũmń##--!!]",
      "SectionPropertyPaneTitle": "[!!--##Şȇčŧıơƞ##--!!]",
      "SectionPropertyPaneColumnGroupName": "[!!--##Ľăȳơűť ơƿŧįơňş##--!!]",
      "ToolbarSelectZone": "[!!--##Şēŀȅĉţ šēċŧįőņ##--!!]",
      "DragIconFallbackRTEText": "[!!--##Ťȇxť##--!!]",
      "DragZoneHandleTitle": "[!!--##Ƥřęśš Ĕńţĕŕ ŏř Şƥäčė ŧŏ ėňťȇř mŏvȅ mōđė##--!!]",
      "DragZoneMoveStarted": "[!!--##Ƥŕēśś ũƿ āŗŗōŵ ĸěƴ ţō mōvȇ ůƿ ȃńď đơŵň ȁřŗōŵ ĸęȳ ťơ mővȅ ďőŵŋ. Ƥŕėŝś Ėŉţęŗ ťŏ ċơņƒīŕm ŧħē mŏvē. Ƥŗěŝś ęşċãƿę ťŏ ćãņċēļ ťĥȇ mōvĕ. ##--!!]",
      "DragZoneMoveComplete": "[!!--##Mővěđ ŵėƀ ƥâŕŧ ƒŗơm {0} ťŏ {1}. ##--!!]",
      "DragZoneMoveCompleteZone": "[!!--##Mōvȅď şęċťıőŉ ƒřơm {0} ťő {1}##--!!]",
      "DragZoneMoveCancelled": "[!!--##Mōvę ĥāŝ ƀȇěń ćăňćĕľłėď.##--!!]",
      "DragZoneMoveNotAllowedAriaLabel": "[!!--##Ċàŉ'ţ mơvē áņɏ ƒũŕťħěŕ ĩň ŧħáţ đıŗĕčŧıơƞ, őŗ mővę ıś ňōţ åŀŀŏŵȇđ ŧŏ ŧħåť śȅĉŧīōņ##--!!]",
      "DragZoneMoveNotAllowed": "[!!--##Mŏvȇ ńőť ǻłłŏŵęđ##--!!]",
      "DragZoneMoveInsideLevelControl": "[!!--##Ƥơŝĩţĩŏň {0}##--!!]",
      "DragZoneMoveInsideLevelSection": "[!!--##Ċơļųmŉ {0}, ƥōśīťıŏň {1}##--!!]",
      "DragZoneMoveInsideLevelZone": "[!!--##Śęćŧıŏŉ {0}, ċōľũmň {1}, ƥŏšıŧīōƞ {2}##--!!]",
      "WebPartAriaLabel": "[!!--##ŵȇƅ ƥăŗţ##--!!]",
      "SectionContextualAriaLabel": "[!!--##{0}, {1} šěċťıōŋ čơƞţàĭņīņġ {2}##--!!]",
      "SectionAriaLabel": "[!!--##şėċţįőƞ##--!!]",
      "WebPartsInSectionLabel": "[!!--##{0}, {1}##--!!]",
      "ToolboxHintSectionTitleOnlyLayouts": "[!!--##Āđđ ȃ ņěŵ ŝęčťıŏň##--!!]",
      "ToolboxHintTitleWithLayout": "[!!--##Ăđď á ńĕŵ ŵȅƂ ƥäřť ĩň {0}##--!!]",
      "ToolboxHintColumnOne": "[!!--##ĉơĺůmń ơŋȇ##--!!]",
      "ToolboxHintColumnTwo": "[!!--##čōľūmņ ťŵō##--!!]",
      "ToolboxHintColumnThree": "[!!--##čơľũmņ ŧħŕęě##--!!]",
      "EmptySectionAriaLabel": "[!!--##ŉơ ŵęƂƿǻŕţ##--!!]",
      "SectionPositionAriaLabel": "[!!--##Šēćŧĭơň {0} ơƒ {1}##--!!]",
      "CloseButtonAriaLabel": "[!!--##Čļőšē##--!!]",
      "DeleteConfirmationLabel": "[!!--##{0} ĥãŝ ƀēęƞ ďēļȅŧěđ.##--!!]",
      "NarrowModeDialogTitle": "[!!--##Ŵīđēŋ ŷơůŕ ɓŕőŵŝėŕ ŵīƞďōŵ##--!!]",
      "NarrowModeDialogSubtitle": "[!!--##Ęđĭŧĭƞğ įş ƞŏţ ȁvąĩľåƄŀĕ īņ á ŋàŕŗōŵ Ƃŗơŵšėř ŵīŋđōŵ. Mȁĸę ťĥȅ ŵĭŉđŏŵ ŵıđėř ţơ ĉōŉťıńũȇ ȅđįţĭŉğ.##--!!]",
      "DialogDescription": "[!!--##{0} ďĭäŀōğ {1}##--!!]"
    },
    "_yMeGkKybrchrRl4dKHORJw": {
      "FormattingBarAlignCenterButtonTitle": "[!!--##Ċęňţěŗ##--!!]",
      "FormattingBarAlignLeftButtonTitle": "[!!--##Ȃļįĝŉ ŀėƒţ##--!!]",
      "FormattingBarAlignRightButtonTitle": "[!!--##Ǻĺıģƞ řįĝĥţ##--!!]",
      "FormattingBarBoldButtonTitle": "[!!--##ʙơŀď (Čťŗļ+ʙ)##--!!]",
      "FormattingBarBulletListButtonTitle": "[!!--##Ɓůŀŀěťěđ ľįşţ##--!!]",
      "FormattingBarClearFormattingButtonTitle": "[!!--##Ċłȇȁŗ äĺŀ ƒơřmäţťįƞĝ##--!!]",
      "FormattingBarConfirmAction": "[!!--##Āćŧıơƞ {0} ƿȅřƒơŗmȇď.##--!!]",
      "FormattingBarConfirmActionOnSelection": "[!!--##Ãċţįőń {0} ƥȅŕƒŏřmȇđ ơŋ şȇłēčţĕď ţėxť: {1}##--!!]",
      "FormattingBarNormalTextButtonTitle": "[!!--##Ŋŏŗmąŀ ťėxţ##--!!]",
      "FormattingBarHeading2ButtonTitle": "[!!--##Ħȇąďĭƞġ 1##--!!]",
      "FormattingBarHeading3ButtonTitle": "[!!--##Ħěǻďıńğ 2##--!!]",
      "FormattingBarHeading4ButtonTitle": "[!!--##Ĥȅȁđįŋĝ 3##--!!]",
      "FormattingBarQuoteButtonTitle": "[!!--##Ƥűŀļ ǭŭŏŧē##--!!]",
      "FormattingBarItalicButtonTitle": "[!!--##Ĩŧáĺįĉ (Čŧŕľ+İ)##--!!]",
      "FormattingBarLinkButtonTitle": "[!!--##Ĥŷƿěřĺīńķ##--!!]",
      "FormattingBarNumberedListButtonTitle": "[!!--##Ņűmƃĕŕȅđ łīśţ##--!!]",
      "FormattingBarUnderlineButtonTitle": "[!!--##Ůŉďȇřļĩŋȅ (Čţŕľ+Ū)##--!!]",
      "FormattingBarUnlinkButtonTitle": "[!!--##Řęmŏvē ŀıŉķ##--!!]",
      "FormattingBarMoreButtonTitle": "[!!--##Mőŗė##--!!]",
      "UndoButtonTitle": "[!!--##Ųƞďō (Ċţřŀ+Ž)##--!!]",
      "RedoButtonTitle": "[!!--##Ʀėďő (Ĉţŕŀ+Ŷ)##--!!]",
      "FormattingBarAccessibleLabel": "[!!--##Ƒơŗmàťţıņğ##--!!]",
      "LinkDialogErrorNotSupportedLink": "[!!--##Ťħīŝ ľıŉƙ ţɏƥę ĭš ŉơŧ šųƥƥōŗŧĕď.##--!!]",
      "LinkDialogTextFieldAriaLabel": "[!!--##Ŵėƅ ãďďŕěśš ţơ ļīņƙ ţŏ##--!!]",
      "LinkDialogTextFieldLabel": "[!!--##ŴĕƂ ȁďďřěşş:##--!!]",
      "LinkDialogDisplayTextFieldLabel": "[!!--##Ťēxŧ ţō đīśƿļàŷ:##--!!]",
      "LinkDialogTitle": "[!!--##İŉšęŗŧ ĺĭŉƙ##--!!]",
      "RichTextEditorAriaLabel": "[!!--##Ŧěxţ ęďĭţơŕ. Ůşē Ȃĺţ+Ƒ10 ťơ ğŏ ťő ťơơĺɓàŕš.##--!!]",
      "RichTextEditorTitle": "[!!--##Ŧĕxť ĕďĩŧơŕ##--!!]",
      "RichTextEditorIframeTitle": "[!!--##{0} {1}##--!!]",
      "RichTextLinkDialogCancelButtonLabel": "[!!--##Čǻƞĉȅŀ##--!!]",
      "RichTextLinkDialogSaveButtonLabel": "[!!--##Šãvę##--!!]",
      "RichTextNavigationAltF10Keys": "[!!--##{0} {1}##--!!]",
      "TextWebPartPlaceholder": "[!!--##Ŧȳƿě ŷŏũŕ ťęxţ ĥęřě##--!!]",
      "ToolbarNavigationArrowKeys": "[!!--##Űśȇ åŕřőŵ ĸȇɏş ŧő ňąvıģäŧĕ ĩƞŝĭđē ţħĕ ŧơőľƀàŗ.##--!!]",
      "ToolbarNavigationTabKeys": "[!!--##Ŭšȇ ţâƅ ťō šŵįţćħ ɓȇţŵȇȇŉ ţőŏľƅăŕŝ.##--!!]",
      "ToolbarNavigationShiftTabKey": "[!!--##Ůşę ŝĥĩƒť + ŧàƃ ťő ńāvıĝăţȅ Ƅâćķ ŧő ţėxťƄŏx##--!!]",
      "ImagesWithTextNotSupported": "[!!--##Ĉàŉ'ŧ ƥȃşťě įmăğē ŵīťħıņ ţėxţ, ťãƅļē, łĩśť ŏŗ mūŀťįƿļȇ įmâģȅś ăť ŏņĉę. Ƥĺěăśę ƥàŝťě ȅȁčĥ įmåģȇ\r\n    īƞďĭvĩďūáŀĺȳ.##--!!]",
      "ImagesInTableNotSupported": "[!!--##***Ċåń'ť ƥâśťȅ īmãğȇ īƞŝįďĕ ťăƂĺė. İŋļĩņę ĭmàĝȇş ăřē ƞōť şųƥƥơŕťȇđ.##--!!]",
      "CloseWarningText": "[!!--##Ĉłŏşē ŵāŗňĭňġ {0} ##--!!]",
      "LoadingText": "[!!--##Ƥăšŧĩŉġ...##--!!]",
      "AddRowAboveText": "[!!--##Ĭŉśėŗť àƃơvě##--!!]",
      "AddRowBelowText": "[!!--##Īŋśēŗť ƃĕłơŵ##--!!]",
      "DeleteRowText": "[!!--##Đēľęţę ŗŏŵ##--!!]",
      "AddColumnLeftText": "[!!--##İņšȇŗţ ĺēƒţ##--!!]",
      "AddColumnRightText": "[!!--##Ĭńšěŕť ŗīģĥŧ##--!!]",
      "AddRowAboveShortcutText": "[!!--##{0} (Ĉţŕĺ+Şĥıƒť+Á)##--!!]",
      "AddRowBelowShortcutText": "[!!--##{0} (Ĉŧŗĺ+Śħĩƒŧ+Ź)##--!!]",
      "DeleteRowShortcutText": "[!!--##{0} (Ċťřĺ+Šĥįƒţ+Ɖ)##--!!]",
      "RTESettingsText": "[!!--##Ťėxŧ ąňď ŧăɓļĕ ƒŏŕmäťťīƞĝ##--!!]",
      "FontDropDownText": "[!!--##Ƒőņť şťȳĺĕ##--!!]",
      "StrikeThroughButtonLabel": "[!!--##Šţřıķėţħŕŏŭġħ##--!!]",
      "SuperscriptButtonLabel": "[!!--##Śŭƥĕŕśčŕīƥŧ##--!!]",
      "SubscriptButtonLabel": "[!!--##Ŝůƅşčŕīƿŧ##--!!]",
      "ParagraphGroupText": "[!!--##Ƥãŕǻġŕäƥħ##--!!]",
      "JustifyButtonLabel": "[!!--##ĵųŝţįƒȳ##--!!]",
      "IncreaseIndentButtonLabel": "[!!--##Ĭƞćřēäŝȅ ĩƞďēńŧ##--!!]",
      "DecreaseIndentButtonLabel": "[!!--##Đȇĉŕȅâşę įŋďĕŉţ##--!!]",
      "FontSizeDropDownLabel": "[!!--##Ƒơƞť šıźȇ##--!!]",
      "TableTitle": "[!!--##Ŧãɓľė##--!!]",
      "TableGroupLabel": "[!!--##Ţäɓľě (Ƥŕȅvįȇŵ)##--!!]",
      "TableGroup": "[!!--##ŢǻƂŀē##--!!]",
      "TableButtonLabel": "[!!--##Īŋšĕŕŧ ťäƂłę##--!!]",
      "InsertAndDeleteGroupLabel": "[!!--##Īńŝȇŗť ąƞď đěłěŧĕ##--!!]",
      "InsertRowBeforeButtonLabel": "[!!--##İƞŝĕřŧ äƀōvě##--!!]",
      "InsertRowAfterButtonLabel": "[!!--##Ĩƞšēřŧ ƃĕŀŏŵ##--!!]",
      "InsertColumnLeftButtonLabel": "[!!--##Īņšēŕŧ ĺėƒť##--!!]",
      "InsertColumnRightButtonLabel": "[!!--##Īƞŝěŕţ řıġĥţ##--!!]",
      "DeleteRowButtonLabel": "[!!--##Ďēĺȅţė ŕŏŵ##--!!]",
      "DeleteColumnButtonLabel": "[!!--##Ɗȇŀȇŧę čŏľųmň##--!!]",
      "DeleteTableButtonLabel": "[!!--##Ɗėŀėţę ťáƅľě##--!!]",
      "FontColorLabel": "[!!--##Ƒőņţ ćơľơř##--!!]",
      "StandardColorLabel": "[!!--##Šťäņđåŗđ ćŏŀơŗŝ##--!!]",
      "DefaultColorLabel": "[!!--##Ąűťŏmăŧįč##--!!]",
      "RedDarkLabel": "[!!--##Đàřƙ ŕęđ##--!!]",
      "RedLabel": "[!!--##Řėď##--!!]",
      "YellowLabel": "[!!--##Ɏȇļľōŵ##--!!]",
      "GreenLightLabel": "[!!--##Ľĭġĥť ģŕěęń##--!!]",
      "GreenLabel": "[!!--##Ġŕȅȅŋ##--!!]",
      "GreenDarkLabel": "[!!--##Ɖářĸ ğŗȇěŋ##--!!]",
      "BlueLightLabel": "[!!--##Ļįğĥť ƃĺūę##--!!]",
      "BlueLabel": "[!!--##ßľųȅ##--!!]",
      "BlueDarkLabel": "[!!--##Ɗáŕĸ ƅļũě##--!!]",
      "PurpleLabel": "[!!--##Ƥůřƿŀę##--!!]",
      "HightlightLabel": "[!!--##Ħĭĝħļĩġĥť čōŀőŗ##--!!]",
      "HightlightColorsLabel": "[!!--##Ħĭĝħŀĩĝħť čōļơřş##--!!]",
      "PinkLabel": "[!!--##Ƥıƞķ##--!!]",
      "OrangeLabel": "[!!--##Ơŗȃŉĝĕ##--!!]",
      "RemoveHighlightColor": "[!!--##Ŋő ĉŏľơř##--!!]",
      "HyperlinkGroupLabel": "[!!--##Ĥŷƥȇřļĩƞĸ##--!!]",
      "TealLabel": "[!!--##Ŧėäł##--!!]",
      "MagentaLabel": "[!!--##Māğěņţá##--!!]",
      "AquaLabel": "[!!--##Ȃǭůā##--!!]",
      "MaroonLabel": "[!!--##Màŕŏơň##--!!]",
      "GoldLabel": "[!!--##Ĝơļď##--!!]",
      "GreyLabel": "[!!--##Ġŕęŷ##--!!]",
      "DarkGreyLabel": "[!!--##Đāŕĸ ģŗęƴ##--!!]",
      "BlackLabel": "[!!--##Ƀŀąċĸ##--!!]",
      "ThemeColorGroupLabel": "[!!--##Ţĥěmĕ ċơłōŕš##--!!]",
      "ThemeDarkerLabel": "[!!--##Ŧĥēmȇ đáŗĸĕř##--!!]",
      "ThemeDarkLabel": "[!!--##Ŧĥȅmĕ đâŗķ##--!!]",
      "ThemeDarkAltLabel": "[!!--##Ţĥĕmė ďãŕķ âľţěŗńâŧĕ##--!!]",
      "ThemePrimaryLabel": "[!!--##Ţħĕmė ƥŕīmāŕƴ##--!!]",
      "ThemeSecondaryLabel": "[!!--##Ţĥėmȇ śȇčőņďäřŷ##--!!]",
      "NeutralDarkLabel": "[!!--##Ňȅűŧŕǻľ đăŗķ##--!!]",
      "NeutralPrimaryLabel": "[!!--##Ńȅūţřǻĺ ƿŕımâŕŷ##--!!]",
      "NeutralPrimaryAltLabel": "[!!--##Ɲęūťŗåľ ƿŕĭmăŗƴ àłťȅřƞāŧę##--!!]",
      "NeutralSecondaryLabel": "[!!--##Ɲėųťŕãŀ śȇĉőŉďăřȳ##--!!]",
      "NeutralTertiaryLabel": "[!!--##Ŋěűŧřăľ ţęŕťĭâŗȳ##--!!]",
      "TableStylesGroupLabel": "[!!--##Ţȃƀĺę šťŷľěş##--!!]",
      "SimpleTableButtonLabel": "[!!--##Ƥľăįƞ##--!!]",
      "TableWithHeaderBorderLabel": "[!!--##ŞũƂťĺȇ ĥėäđȇŗ##--!!]",
      "TableWithFilledHeaderLabel": "[!!--##Ħȇąďȅř##--!!]",
      "TableWithBandedRowsLabel": "[!!--##Âľŧėřƞáťĭƞĝ ŕőŵś##--!!]",
      "TableWithBandedRowsAndColumnsLabel": "[!!--##Ćơłųmņ ĥěǻďėŗ##--!!]",
      "SimpleTableButtonThemeLabel": "[!!--##Ŧĥȅmě-čơĺōŗȇď ƥŀáıń##--!!]",
      "TableWithHeaderBorderThemeLabel": "[!!--##Ţħėmė-čōĺōřęđ śūƅţĺě ĥęäđēŗ##--!!]",
      "TableWithFilledHeaderThemeLabel": "[!!--##Ťĥěmē-ĉơĺōŗȅđ ħęàđěŗ##--!!]",
      "TableWithBandedRowsThemeLabel": "[!!--##Ŧħēmę-ċőŀŏřėđ āĺťęŕƞȃŧĭńğ ŗơŵš##--!!]",
      "TableWithBandedRowsAndColumnsThemeLabel": "[!!--##Ŧħȅmė-čŏļōŗěď ċŏŀũmņ ħęȁđēŕ##--!!]",
      "AlignTableGroupLabel": "[!!--##Ţăƅĺė äĺĩĝńmēŋŧ##--!!]",
      "AlignTableLeftLabel": "[!!--##Åĺığň ŧāƃĺȅ łėƒŧ##--!!]",
      "AlignTableCenterLabel": "[!!--##Äĺīĝņ ŧȁƂŀȇ čȅňŧēŕ##--!!]",
      "AlignTableRightLabel": "[!!--##Ãļįğŋ ŧáɓŀĕ řĭĝħŧ##--!!]",
      "RTEPagePickerSaveAction": "[!!--##Ŧħě łīńƙ {0} īŝ ąďďȅď.##--!!]",
      "RTEPagePickerUnlinkAction": "[!!--##Ŧħȅ ľīňķ {0} ĭŝ ŕȇmōvȇď.##--!!]"
    },
    "_/GZrHjuQO4erDQbBRI2XSA": {
      "DialogTitle": "[!!--##Įŉśěŕť ĺįŉķ##--!!]",
      "UrlTextFieldLabel": "[!!--##Âďđŕęŝš##--!!]",
      "UrlTextFieldAriaLabel": "[!!--##ŴēƂ ăđďŕȅŝś ţơ łĭņƙ ţŏ##--!!]",
      "UrlTextFieldError": "[!!--##Ťĥĭş ľīņĸ ţƴƿĕ įŝ ňōţ śŭƿƿőřťēđ.##--!!]",
      "TitleTextFieldLabel": "[!!--##Ŧȇxţ ţơ đįşƿľāŷ##--!!]",
      "RecentPagesLabel": "[!!--##Mőšţ ŕȅćęņţ ƥåġȇş ōň ŧħĩš şīťė##--!!]",
      "SearchForPagesLabel": "[!!--##Ƥåġęş ōň ţħıš šįţė ťĥãŧ màťćĥ ȳŏųŗ ŝȅąřćĥ##--!!]",
      "NoResultLabel": "[!!--##Ŋơ įţēmš máťčĥ ɏőŭŕ şěàŗċĥ##--!!]",
      "TryAgainLabel": "[!!--##Ŧřɏ ǻ ďĭƒƒȇŗĕƞţ ĸęȳŵōŗď##--!!]",
      "OpenLinkInNewTabLabel": "[!!--##Ơƥĕņ ŀıńƙ įň ǻ ƞȇŵ ŧãƀ##--!!]",
      "SaveButtonLabel": "[!!--##Ŝâvę##--!!]",
      "CancelButtonLabel": "[!!--##Ćäŉĉēľ##--!!]",
      "UnlinkButtonLabel": "[!!--##Řěmővĕ ĺıŉĸ##--!!]",
      "TitleSuggestionsColumnName": "[!!--##Ťīţľě##--!!]",
      "EditorSuggestionsColumnName": "[!!--##Mőďīƒıęď ƀƴ##--!!]",
      "ModifiedSuggestionsColumnName": "[!!--##Mőďīƒīęď##--!!]",
      "PageContentContainsSearchText": "[!!--##\"{0}\" ƒőųŉď įņ ƥǻġě ćŏŉťȇņťş##--!!]",
      "CurrentPage": "[!!--##(ĉűřřȇņţ ƿāğĕ)##--!!]",
      "SearchTextFieldLabel": "[!!--##Ŝěȃŗćĥ##--!!]",
      "SearchTextFieldPlaceholder": "[!!--##Ěńťęŗ ķěɏŵōŗďś ţō şėáŗċĥ ƒơŗ ƿȃĝęš ōň ţħĭŝ śīŧȅ##--!!]",
      "DialogAriaDescription": "[!!--##Ĩņşęŗţ à ľīƞƙ ţơ â ƿȃĝȇ ơń ŧħȅ ċŭŗŕȅňť šĭŧė ōŕ ţō ǻ ƥáġȅ ōń àńőŧĥēŕ śıťȅ.##--!!]",
      "SuggestionsListAriaLabel": "[!!--##Şēłĕčŧ ä ƥȁĝȇ ƒŕơm ťĥę {0} ľīşť. Ƥŕěśś ŧĥȅ Ųƥ āņď Ɖơŵƞ āřŗơŵ ƙȅƴś ťő ŉävıģàţę ťħŗơůğħ ŧĥȇ ƿâĝēś. Ƥŕȅšś ŧĥė Ŝƿąċė ķěȳ ťő šěľęčŧ ȁ ƿáģė. Ŵħĕņ ã ƥȃġė īş ŝĕĺěċţȇđ, ťĥȇ ƿȃġȇ ļįņĸ ŵĭļł ƅȅ ůşĕď ĭŋ ŧĥę Ľıŋĸ ıńƿųţ ƀŏx, áŋđ, ĩƒ ťħēŗę īš ňő ţěxť ıŋ ťħȇ Ţĕxţ ŧő ďįšƥłăɏ ıňƿųţ ƃőx, ŧĥȅ ƿȃĝĕ ŧĭŧľȇ ŵĩŀĺ ƅę ųŝėď.##--!!]",
      "SaveButtonDisabledScreenReaderAlert": "[!!--##Ţĥȇ Ŝăvę ƅũţŧơŋ ĩś ņơŧ āvâįŀãƀŀė ɓēĉąŭšė ǻň ıńväļīđ ŵȅƀ ȃďďřȅšŝ ŵȁş ēŋţęŗĕď.##--!!]",
      "SaveButtonEnabledScreenReaderAlert": "[!!--##Ťĥĕ Şǻvȇ Ƃũţťōƞ ış ąväįłåƃĺȅ.##--!!]",
      "PageIsSelectedScreenReaderAlert": "[!!--##Ŧĥȇ ƿàĝě {0} įş şȇłēćťĕď.##--!!]",
      "IsSearching": "[!!--##Ŝȅȃŗćħīňġ...##--!!]",
      "SearchResultsShowing": "[!!--##Ŝȅàŕćħ ŕęšűĺŧś åřė ďĩšƿŀâɏȅđ. Ƥŕēŝś Ťâɓ ŧő ġő ŧơ ŧĥȇ Şęǻŗċĥ řĕśűŀŧś ŀıšŧ.##--!!]",
      "RecentPagesShowing": "[!!--##Ā ĺīšť ơƒ řȅĉęņŧ ƿåġēŝ įś đĩŝƿŀȁɏĕď. Ƥřęšś ŦȁƂ ţő ĝō ťō ţĥė Ʀēćęƞť ƿãġėş ļīšť.##--!!]"
    },
    "_4SOrKBlkyRLkXWcT6txoow": {
      "ToolboxSearchAccessibleLabelTemplate": "[!!--##Ŧƴƿē ĥęŗē ŧơ šęāŗćĥ ƒơŕ ā ŵęƀ ƥāŕţ. {0}##--!!]",
      "ToolboxSearchEscapeAccessibleLabel": "[!!--##Ƥřēşš Ĕšĉąƥȇ ŧō ċłȅáŕ ŧĥę ėxĩŝŧīŋğ ŝȅâŕĉĥ.##--!!]",
      "ToolboxSearchLabel": "[!!--##Ŝęâŕĉħ##--!!]"
    },
    "_6tOZemhV08aF1IgNDNeiwQ": {
      "ToolboxGroupNameFullWidth": "[!!--##Ÿơů ċåń ǻďđ ŏŉȇ ơƒ ŧħėŝē ŵȇƅ ƿáŗţŝ ťō ŧħīš ƒůĺļ-ŵĭďťĥ čőľŭmƞ##--!!]"
    },
    "_NS+5Kf9zpnH1/LStsp+Tfw": {
      "ToolboxCategoryTextMediaAndContent": "[!!--##Ŧĕxť, mēđīă, âƞď ċőņŧȅŉţ##--!!]",
      "ToolboxCategoryDiscovery": "[!!--##Ɖĩśĉŏvęŗȳ##--!!]",
      "ToolboxCategoryCommunicationAndCollaboration": "[!!--##Čőmmŭŋįčåťįōŉ ȃƞď čōļļâƄōŗàŧĩōņ##--!!]",
      "ToolboxCategoryPlanningAndProcess": "[!!--##Ƥļãŋņįņğ ȃŋđ ƥřőċěśś##--!!]",
      "ToolboxCategoryBusinessIntelligence": "[!!--##ʙūŝıńėŝš ǻŉď įńťĕĺļīġęņĉě##--!!]",
      "ToolboxCategorySiteTools": "[!!--##Śıţȇ ťőōłŝ##--!!]",
      "ToolboxCategoryConnectors": "[!!--##Ċơńńėčŧŏřş##--!!]",
      "ToolboxCategoryOther": "[!!--##Őťĥēŗ##--!!]",
      "ToolboxGroupNameFeatured": "[!!--##Ƒěāţŭŗėđ##--!!]",
      "ToolboxGroupNameAlphabetical": "[!!--##Ȃĺļ Ą ťơ Ƶ##--!!]"
    },
    "_RRzf46hnc4+fBX8RHyocNg": {
      "TextWebPartDisplayName": "[!!--##Ţȇxŧ##--!!]",
      "TextWebpartDescription": "[!!--##Åďđ áņđ ƒŏřmåŧ ťěxţ##--!!]"
    },
    "_2TT4IG31kAjRqhD0h5kPOg": {
      "ToolboxGroupSeeAllButtonLabel": "[!!--##Ŝĕē ȃĺľ##--!!]",
      "ToolboxGroupSeeAllButtonAriaLabel": "[!!--##Šěę ȃļĺ ŵȅƄ ƥãŗŧš ĩņ {0}.##--!!]",
      "ToolboxGroupAriaLabel": "[!!--##{0} ĺıśţ. Ųŝę łěƒţ ȁŉď ŗĭĝĥť ȁŕŕőŵ ĸēȳş ŧơ mŏvę ŵĩţĥĩň ŧĥě ĺıŝŧ.##--!!]"
    },
    "_WVn4QXYnL8WpGCqr2C9ySA": {
      "ToolboxCategoryAllCategory": "[!!--##Āłĺ ɓŷ ćàţȇġōŗȳ##--!!]",
      "ToolboxCategorySortingCategory": "[!!--##Ãĺļ Ȁ ŧő Ž##--!!]",
      "ToolboxCategorySearchResults": "[!!--##Šēãŕćĥ řěşůłťš##--!!]",
      "ToolboxCollapseButtonDescription": "[!!--##Ŗęŝťŏřę ŧō őŕĩĝıņãľ ŝĩžȇ##--!!]",
      "NoResultLabel": "[!!--##Ņō īťȅmś mäţćħ ŷŏŭř šēǻřćħ##--!!]",
      "TryAgainLabel": "[!!--##Ţŕŷ á đīƒƒȇřěńţ ƙēɏŵōřđ##--!!]",
      "LargeToolboxAriaTitle": "[!!--##Ĕxƥǻŉďěđ ŵęƀ ƥàŗť ťőōľƃōx.##--!!]",
      "LargeToolboxAriaSubTitle": "[!!--##Ŧħȇŕę ăřē {0} įťēmś ĩƞ ţħē ŧơőļƃőx.||Ţĥėŗě åřė {0} ĩŧĕm ıň ŧħę ţőőŀɓơx.||Ťħȅŕē âŕȅ {0} ĩťēmş įƞ ŧĥę ŧơŏľƃōx.##--!!]",
      "ToolboxCollapseButtonAriaLabel": "[!!--##Ćőļĺáƿšė.##--!!]",
      "CountStringIntervals": "[!!--##0||1||2-##--!!]",
      "DropDownMenuAriaLabel": "[!!--##Šħōŵįƞģ ŵėɓ ƿȃŕťš ƒŕơm {0} ĉȁťēģōŗɏ.##--!!]",
      "SwitchCategoryAlert": "[!!--##Ĉħâŋĝȅđ ťō {0}.##--!!]",
      "BackButtonAriaLabel": "[!!--##Ĝō Ƃąćƙ ŧơ ťħȅ ƿŕēvĩōūŝ vīěŵ.##--!!]"
    },
    "_CZsUWMvZilAKKAfwQSdzKQ": {
      "ToolboxExpandButtonTitle": "[!!--##Ēxƥäņđ ŧō śȅě mōŕĕ ŵēƅ ƿåŕţş##--!!]",
      "ToolboxNoItemsFound": "[!!--##Ŵȇ ċŏũļďŋ'ţ ƒĩŉď âņɏţħĭŉġ ŧħāť māţĉĥėŝ ȳőűŕ ŝēąŗćĥ.##--!!]",
      "ToolboxSectionHeader": "[!!--##Ŝěčţĭőň ļàƴőũţ##--!!]",
      "CanvasItems": "[!!--##{0} ŵȇƃ ƥâŗŧś đışƿŀăŷěđ įń ŧĥȇ ţőōľƄŏx.||{0} ŵēƄ ƿãřť đīşƿľǻɏěđ įŋ ŧħė ŧōŏľƃōx.||{0} ŵěƂ ƥàŗŧŝ ďīŝƿŀàŷěď ĭŉ ŧħȇ ťơōłƀōx.##--!!]",
      "CanvasItemsInterval": "[!!--##0||1||2-##--!!]"
    },
    "_NAR8NFw8cblGJm9t5CjqOw": {
      "SuccessfullyLoadedText": "[!!--##Šŭćċēşšƒůľĺɏ ŀơąđȇď ďėƅũġ mâŋĩƒȅŝŧś.##--!!]",
      "ErrorLoadingText": "[!!--##Ƒáıļėď ťō ľŏäď đȅɓűğ mȁňĭƒēşţş: {0}##--!!]"
    },
    "_vd/LT/qfiQhbHFfeM1GtlA": {
      "FetchFailedError": "[!!--##***Ƒȅţčħĩņġ ŵĕƀƿǻŧş ƒāĭłėď ŵīţħ ȅŕŕơŕ \"{0}\". Ŕĕƞďėŕ ōƒ ȃ ċãćħěď ŵơŗƙƂȅńċĥ măŷ ƒäıĺ.##--!!]"
    },
    "_FQya7ZjwIyrOEutOa+omIA": {
      "Title": "[!!--##Ŵāŗŋįŉĝ##--!!]",
      "SubText": "[!!--##Ŷōůŗ ŵĕƃ ƿåŗť ŵĩłľ ńőţ ąƿƿęåŕ ıň ťħĕ ŧơŏłƄơx. Ƥľȇȃśė máƙȅ ŝųŗĕ \"ğųŀƿ ŝěŕvę\" īŝ ŕųŋňīŋğ ıŋ á ŵėƃ ƥáŗť ƥŕŏĴēċţ. Ƥĺĕâśė ŗėƒŕėšĥ ťħȅ ƿȁģȇ ơŋĉē \"ĝūĺƿ śěřvȇ\" ĩş ŕũƞņīŉĝ.##--!!]",
      "OkButtonText": "[!!--##ŐƘ##--!!]",
      "ClickHerePrefix": "[!!--##Ćłĩċĸ ##--!!]",
      "ClickHereLink": "[!!--##ĥȅřė##--!!]",
      "ClickHereSuffix": "[!!--## ƒōŕ mŏŕȅ ıƞƒŏŕmàŧĩőń.##--!!]"
    },
    "_1JArBGDet5Uj9pJOV/9sFw": {
      "UrlTextBoxPlaceholder": "[!!--##Ȇƞŧȇŗ à ŰŘŁ ťő vĭėŵ ĭń Mőƃĩłę Ƥřęvıĕŵ Ťőőļ.##--!!]",
      "ScreenReaderMobilePreviewEntered": "[!!--##Ÿơū ħȁvȅ ęņţęřēđ ţħē Mŏƅīĺė Ƥřėvīēŵ Ťŏōľ. Ĭƒ ȳơŭ ŵȁŋť ţŏ ƥŕēvįěŵ â ďīƒƒȇŕȅƞť ƥäġȇ, ęŋŧěř ŧħȇ ŪƦĿ ıň ŲŘŁ ŧȅxŧ ƒįĕļď. Ŧơ ĉŀơśĕ ŧħē ťőōĺ ȃƞď ġő Ƅāĉĸ ţơ ŴōřĸƄęŋčĥ, ƥŕěśŝ Ėśċǻƿę.##--!!]",
      "ScreenReaderDevicePickerEntered": "[!!--##Ųŝė ľȇƒŧ ąńđ ŗįĝĥţ äŕŗőŵ ĸēŷš ŧő čħőōśȅ ą ďěvĩčĕ ŧŏ ĉħāƞģȇ ťħȇ ƥŗĕvįēŵ šċŕěȇň śīƶȅ.##--!!]",
      "ScreenReaderDevicePickerSelectionChanged": "[!!--##Ƥŗēšŝ Ėƞţėŕ ťŏ ćħőőşȇ ťĥīś ďēvįčė.##--!!]",
      "Width": "[!!--##Ŵıďţħ##--!!]",
      "Height": "[!!--##Ĥēįģħŧ##--!!]"
    },
    "_8EVKOH1av6NjR/ZNfdafrw": {
      "WebPartData": "[!!--##***ŴęƄ Ƥàŗţ Ďäťȃ##--!!]",
      "ClassicPages": "[!!--##Čĺȁşŝĩč Ƥãĝėś##--!!]",
      "ModernPages": "[!!--##Mŏđȇŕń Ƥāģȅş##--!!]",
      "Close": "[!!--##Ĉľŏşȇ##--!!]",
      "WebPartDataHelpInfoLink": "[!!--##***Ĺĕǻŗń ǻƃőůť ƿřơvīšīőňįŉğ ŚĥȃřēƤơĭŉţ åšśȅŧš ƒŗőm ŷŏŭŗ ŠħāřȇƤőīńť ĉļĭȅňť-ŝĩđȅ ŵȇƅ ƥąŗţ##--!!]"
    },
    "_IusqdbcSoVYQiit3+QRSxw": {
      "Office365Title": "[!!--##Ŏƒƒīčė 365##--!!]",
      "SharePointWorkbenchTitle": "[!!--##ŜĥăŗėƤőĭńţ Ŵơřķƅěńčħ##--!!]",
      "ScreenReaderDisplayModeSwitchToEditMode": "[!!--##Śŵıţĉĥĕď ƒŕơm ƿřěvıěŵ mơďĕ ŧŏ ęďıţ mōďė.##--!!]",
      "ScreenReaderDisplayModeSwitchToReadMode": "[!!--##Ŝŵĭţĉħȇď ƒřơm ĕđīŧ mơđė ťŏ ƥřēvĭėŵ mōďē.##--!!]"
    },
    "_nCtJlVOXBHa59LgYtajnjA": {
      "Save": "[!!--##Şăvē##--!!]",
      "SaveAltText": "[!!--##Ũşę ťō šȁvȇ ŧĥȅ ĉŭŕŕĕńť ŵŏŕĸƅēŋćĥ šţȁŧĕ.##--!!]",
      "Discard": "[!!--##Ďīśċāřđ##--!!]",
      "DiscardAltText": "[!!--##Űšė ţő đĩşċȃŕđ ŧĥě ċűŕŕěņţ ŵơŗƙƄȇńċħ ŝţǻţĕ.##--!!]",
      "Mobile": "[!!--##Mŏƃıľĕ##--!!]",
      "MobleAltText": "[!!--##Űşȇ ŧō ŏƥěŉ ŧĥě mōƃĩŀę ƥřęvįȇŵ ţŏơĺ ƒơŕ ȃ ċȅĺļ ƥħőŉė.##--!!]",
      "Tablet": "[!!--##ŤåƂĺȅţ##--!!]",
      "TabletAltText": "[!!--##Ųšȅ ŧơ ŏƥēņ ţħȇ mōƃīľȅ ƿŕȇvīĕŵ ŧőōļ ƒŏř á ţãƄŀěť.##--!!]",
      "Preview": "[!!--##Ƥřęvįęŵ##--!!]",
      "PreviewAltText": "[!!--##Ųśĕ ŧŏ śŵĭťčĥ ƒŗơm ĕđıť mőđē ţő ƿŕěvĭȅŵ mōďę.##--!!]",
      "Edit": "[!!--##Ėďĭţ##--!!]",
      "EditAltText": "[!!--##Ũśę ţō ŝŵĩţċĥ ťŏ ęďıť mōďĕ.##--!!]",
      "WebPartData": "[!!--##***Ŵęƅ ƥȃŕŧ đåŧã##--!!]",
      "WebPartDataAltText": "[!!--##***Đįśƿľàƴ ţĥĕ śěŗĩāļĩżȇď ŵēƂ ƿȃŕť đåŧą.##--!!]"
    }
  };

  strings.default = strings;
  return strings;
});